In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("listings.csv")
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6606,https://www.airbnb.com/rooms/6606,20250925032813,2025-09-25,city scrape,"Fab, private seattle urban cottage!","This tiny cottage is only 15x10, but it has ev...","A peaceful yet highly accessible neighborhood,...",https://a0.muscache.com/pictures/45742/21116d7...,14942,...,4.77,4.88,4.57,str-opli-19-002622,f,3,3,0,0,0.82
1,9419,https://www.airbnb.com/rooms/9419,20250925032813,2025-09-25,city scrape,Glorious sun room w/ memory foambed,This beautiful double room features sun filled...,"Lots of restaurants (see our guide book) bars,...",https://a0.muscache.com/pictures/56645186/e5fb...,30559,...,4.89,4.70,4.69,Exempt,f,10,0,10,0,1.19
2,9596,https://www.airbnb.com/rooms/9596,20250925032813,2025-09-25,previous scrape,"the down home , spacious, central and fab!","We are in a great neighborhood, quiet, full of...","if you arrive early for check in at 3, I reco...",https://a0.muscache.com/pictures/665252/102d18...,14942,...,4.66,4.91,4.56,STR -OPLI-19-002622,f,3,3,0,0,0.56
3,11012,https://www.airbnb.com/rooms/11012,20250925032813,2025-09-25,city scrape,"the orange house, quiet 'n central",NaN,NaN,https://a0.muscache.com/pictures/682034/54bc27...,14942,...,4.72,4.86,4.74,str-opli-19-002622,f,3,3,0,0,0.51
4,25002,https://www.airbnb.com/rooms/25002,20250925032813,2025-09-25,city scrape,Beautiful Private Spot in North Ballard,"-Great eating , Delancey, Fat Hen, 3 blocks aw...",Great walking neighborhood! We are in between...,https://a0.muscache.com/pictures/491561/cf5270...,102684,...,4.98,4.90,4.90,STR-OPLI-19-002617,t,1,1,0,0,6.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6991,1515445606707131986,https://www.airbnb.com/rooms/1515445606707131986,20250925032813,2025-09-25,city scrape,Centrally located private room in shoreline-2,"Private room and bathroom in a townhome, centr...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,127525192,...,NaN,NaN,NaN,STR-OPLI-25-002944,f,3,0,3,0,NaN
6992,1515452490876536616,https://www.airbnb.com/rooms/1515452490876536616,20250925032813,2025-09-25,city scrape,Centrally located private room in Shoreline-3,"Private room and bathroom in a townhome, centr...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,127525192,...,NaN,NaN,NaN,STR-OPLI-25-002944,f,3,0,3,0,NaN
6993,1516340815301554136,https://www.airbnb.com/rooms/1516340815301554136,20250925032813,2025-09-25,city scrape,"Top floor oasis, comfortable and elegant.",This oasis is a perfect place to recover from ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,308306114,...,NaN,NaN,NaN,STR-OPLI-19-803339,f,2,1,1,0,NaN
6994,1516722602078881683,https://www.airbnb.com/rooms/1516722602078881683,20250925032813,2025-09-25,city scrape,"Blueground | West Queen Anne, view, nr Kerry Park","Discover the best of Seattle, with this one be...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,107434423,...,NaN,NaN,NaN,NaN,t,344,344,0,0,NaN
6995,1516825888737631052,https://www.airbnb.com/rooms/1516825888737631052,20250925032813,2025-09-25,city scrape,Modern & Cozy Lower Unit - Great Location,"This is a spacious lower unit, perfect for tho...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,700950408,...,NaN,NaN,NaN,STR-OPLI-25-004870,f,1,1,0,0,NaN

In [3]:
df['last_scraped'].nunique()

1

In [4]:
df_clean = pd.read_csv("clean_data.csv")
df_clean.head()

,Unnamed: 0,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,latitude,longitude,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,1.0,0.82,True,5.0,5.0,True,True,47.65444,-122.33629,...,4.83,4.77,4.88,4.57,False,3,3,0,0,0.82
1,1,1.0,0.97,True,10.0,11.0,True,True,47.55017,-122.31937,...,4.92,4.89,4.70,4.69,False,10,0,10,0,1.19
2,3,1.0,0.82,True,5.0,5.0,True,True,47.65405,-122.33744,...,4.78,4.72,4.86,4.74,False,3,3,0,0,0.51
3,4,1.0,1.00,True,1.0,2.0,True,True,47.67947,-122.37196,...,4.98,4.98,4.90,4.90,True,1,1,0,0,6.06
4,5,1.0,0.00,False,1.0,1.0,False,True,47.63941,-122.32897,...,4.46,4.58,4.83,4.36,False,1,1,0,0,0.35

In [6]:
df_clean = df_clean.drop(columns=["Unnamed: 0"])

bool_cols = df_clean.select_dtypes(include=['bool']).columns
df_clean[bool_cols] = df_clean[bool_cols].astype(int)

In [7]:
df_clean.head()

,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,latitude,longitude,accommodates,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1.0,0.82,1,5.0,5.0,1,1,47.65444,-122.33629,1,...,4.83,4.77,4.88,4.57,0,3,3,0,0,0.82
1,1.0,0.97,1,10.0,11.0,1,1,47.55017,-122.31937,2,...,4.92,4.89,4.70,4.69,0,10,0,10,0,1.19
2,1.0,0.82,1,5.0,5.0,1,1,47.65405,-122.33744,8,...,4.78,4.72,4.86,4.74,0,3,3,0,0,0.51
3,1.0,1.00,1,1.0,2.0,1,1,47.67947,-122.37196,4,...,4.98,4.98,4.90,4.90,1,1,1,0,0,6.06
4,1.0,0.00,0,1.0,1.0,0,1,47.63941,-122.32897,3,...,4.46,4.58,4.83,4.36,0,1,1,0,0,0.35

In [8]:
X = df_clean.drop(columns=["price"])   # target variable
y = df_clean["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
model = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [10]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 114.04277323799796
RMSE: 1546.0809679322504
R2 Score: 0.5296993718324696

## Relevant Column
df_relevant = df_clean[['host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_total_listings_count', 'host_identity_verified', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price', 'minimum_nights', 'maximum_nights', 'has_availability', 'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_communication', 'review_scores_location', 'instant_bookable', 'reviews_per_month']].copy()

In [11]:
df_rel = pd.read_csv("relevant_col.csv")

In [12]:
df_rel = df_rel.drop(columns=["Unnamed: 0"])

bool_cols = df_rel.select_dtypes(include=['bool']).columns
df_rel[bool_cols] = df_rel[bool_cols].astype(int)

In [13]:
df_rel.head()

,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_identity_verified,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_communication,review_scores_location,instant_bookable,reviews_per_month
0,1.0,0.82,1,5.0,1,1,1.0,1.0,1.0,99.0,30,1125,1,161,4.60,4.67,4.77,4.88,0,0.82
1,1.0,0.97,1,11.0,1,2,3.0,1.0,2.0,71.0,2,90,1,220,4.73,4.80,4.89,4.70,0,1.19
2,1.0,0.82,1,5.0,1,8,2.0,3.0,3.0,311.0,30,120,1,98,4.79,4.82,4.72,4.86,0,0.51
3,1.0,1.00,1,2.0,1,4,1.0,1.0,2.0,88.0,2,30,1,1139,4.93,4.92,4.98,4.90,1,6.06
4,1.0,0.00,0,1.0,1,3,1.0,2.0,3.0,154.0,30,730,1,64,4.54,4.72,4.58,4.83,0,0.35

In [14]:
X = df_rel.drop(columns=["price"])   # target variable
y = df_rel["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [15]:
model = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [16]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 50.8430027238679
RMSE: 133.79245194141427
R2 Score: 0.9964781219289834

In [17]:
df_rel['price'].mean()

np.float64(293.8009401185367)